In [14]:
#工件機器限制 K
MachineLimit=[[1,0,1],[1,1,1],[1,0,1],[1,1,1],[1,1,0],
              [1,0,1],[1,1,1],[1,0,1],[0,1,1],[1,1,1]]

#工作時間
ProcessTime=[[80,0,60],[75,86,94],[25,0,96],[78,95,89],[45,78,0],
              [12,0,65],[55,99,87],[11,0,16],[0,16,45],[43,56,21]]

#產生染色體
import random
ChromosomeList=[]
JobResult=[]
for i in range(20):
    gene=random.random()
    ChromosomeList.append(gene)

for s in range(10):
    #單份機率
    sum = 0
    for i in MachineLimit[s]:
        sum += i
    PJ1 =1/sum
    #決定是第幾份(k)
    k=1 #<預設為第一份>
    TotalPJ1=PJ1
    while(ChromosomeList[s]>TotalPJ1):
        k+=1
        TotalPJ1=PJ1*k

    #print(k)

    #工作派給機器(j)
    FinalMachineJ1=0
    sequence=[0,1,2] #機1.2.3
    for j in sequence:
        if(MachineLimit[j]==1):
            k-=1
        if(k==0):
            FinalMachineJ1=j+1 #加回來
            break
    JobResult.append(FinalMachineJ1) 
print(JobResult)          


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [20]:
import numpy as np
test = np.zeros((5, 20))
print(test)
for i in range(20):
    test[0][i]=np.random.rand()
print(test)

b= np.random.rand()
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.10686461 0.62938708 0.58819246 0.41545868 0.14002254 0.507463
  0.00916723 0.23173058 0.84217693 0.88885713 0.7078483  0.87893162
  0.05963028 0.44824118 0.72479728 0.72086784 0.68568945 0.39788378
  0.37146543 0.93389129]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0

In [9]:
#工件機器限制 K
MachineLimit=[[1,0,1],[1,1,1],[1,0,1],[1,1,1],[1,1,0],
              [1,0,1],[1,1,1],[1,0,1],[0,1,1],[1,1,1]]

#工作時間
ProcessTime=[[80,0,60],[75,86,94],[25,0,96],[78,95,89],[45,78,0],
              [12,0,65],[55,99,87],[11,0,16],[0,16,45],[43,56,21]]

#產生染色體
import random
ChromosomeList=[]
for i in range(20):
    gene=random.random()
    ChromosomeList.append(gene)


#單份機率
sum = 0
for i in MachineLimit[s]:
    sum += i
print(sum)


TypeError: unsupported operand type(s) for +=: 'int' and 'list'